let suggestions = [
    'amazon',
    'amazon prime',
    ' airbnb',
    'american airlines',
    'autozone',
    ' apple',
    'a quiet place',
    'whatsapp',
    'best buy',
    'bitcoin',
    'bitcoin price',
    'bmi calculator',
    'calculator',
    'cvs',
    'craigslist',
    'dogecoin',
    'dominos',
    'discord',
    'ebay',
    'elon musk',
    'etsy',
    'quizlet',
    'queen elizabeth',
    'qvc',
    'restaurants near me',
    'red lobster',
    'reddit',
    'real madrid',
    'facebook',
    'fox news',
    'fedex',
    'food near me',
    'google',
    'gmail',
    'google translate',
    'google maps',
    'zoom',
    'zara',
    'zodiac signs',
    'xfinity',
    'xbox',
    'victoria secret',
    'vanguard',
    'vaccine',
    'nba',
    'netflix',
    'news',
    'nascar',
    `mother's day 2021`,
    'linkedin',
    'la liga',
    'louis vuitton',
    'kahoot',
    'knicks',
    'kohls',
    'jetblue',
    `jupiter's legacy`,
    'jcpenney',
    'home depot',
    'happy mothers day',
    'hotmail',
    'maps',
    'mcdonalds',
    'starbucks',
    'spotify',
    'snake',
    'speed test',
    'translate',
    'turbotax',
    'weather',
    'walmart',
    'walgreens',
    'youtube',
    'yahoo',
    'yahoo mail',
    'usps',
    'urban dictionary',
    'instagram',
    'ikea',
    'olive garden',
    'outlook',
    'omegle',
    'paypal',
    'pinterest',
    'pizza hut',
    'what to watch',
    'whataburger',
    'whatsapp web',
    'what time is it',
    'what is aspergers',
    'what is pansexual',
    'what is my ip',
    'what is the weather',
    'what is today',
    'what song is this',
    'what are nfts',
    'what are the symptoms of covid-19',
    'what a wonderful world',
    'what animal is goofy',
    'what about bob',
    'what are capers',
    'what are the 5 love languages',
    'what are adjectives',
]